// Generated by CoffeeScript 1.7.1
(function() {
  var now, xAxis, yAxis;

  now = new Date().getTime();

  xAxis = {
    type: 'datetime'
  };

  yAxis = {
    minPadding: 0,
    maxPadding: 0,
    allowDecimals: false,
    alternateGridColor: '#F4F4F4',
    title: {
      text: 'Total customers'
    }
  };

  superagent.get('/api/customers').end(function(error, res) {
    var allClients, blue, count, graduatedClients, green, grey, handlePointClick, monthAgo, orange, paidClients, pointFormat, red, trialClients, weekAgo;
    if (error || res.status !== 200) {
      console.error('Status: ' + res.status, error);
      $('#container1').text('Status: ' + res.status + ' Message: ' + error);
    }
    grey = '#9E9E9E';
    red = '#D86353';
    green = '#89bf0a';
    orange = '#daa055';
    blue = '#68b0ef';
    allClients = _(res.body).map(function(point) {
      var colour;
      colour = point.delta < 0 ? point.trial_end > point.canceled_at ? (point.event = 'Lost Trial', orange) : (point.event = 'Churned', red) : point.trial_end > now ? (point.event = 'Trial', blue) : (point.event = 'Client', green);
      point.color = colour;
      return point;
    }).value();
    count = 0;
    graduatedClients = [];
    trialClients = _(_.cloneDeep(allClients)).filter(function(point) {
      return point.trial_end != null;
    }).forEach(function(point) {
      var graduatedPoint;
      if (!point.canceled_at) {
        point.color = blue;
        point.event = 'New Trial';
      } else {
        point.event = 'Lost Trial';
      }
      if (point.trial_end < now) {
        graduatedPoint = _.defaults({
          x: point.trial_end,
          delta: -1,
          event: 'Converted from Trial',
          color: green
        }, point);
        return graduatedClients.push(graduatedPoint);
      }
    }).concat(graduatedClients).sortBy(function(point) {
      return point.x;
    }).forEach(function(point) {
      return point.y = (count += point.delta);
    }).value();
    count = 0;
    paidClients = _(_.cloneDeep(allClients)).filter(function(point) {
      return (point.trial_end == null) || point.trial_end < now;
    }).forEach(function(point) {
      if ((point.canceled_at == null) && (point.trial_end != null)) {
        point.x = point.trial_end;
        return point.event = 'Converted from Trial';
      }
    }).sortBy('x').forEach(function(point) {
      return point.y = (count += point.delta);
    }).value();

    /*
     * Initialize the actual graphs
     */
    handlePointClick = function(e) {
      var url;
      url = "https://manage.stripe.com/customers/" + e.point.id;
      return window.open(url, '_blank');
    };
    pointFormat = '{series.name}: <b>{point.y}</b><br /> {point.description}<br /> <b>{point.event}</b>';
    $('#container1').highcharts({
      chart: {
        type: 'line'
      },
      plotOptions: {
        line: {
          color: grey,
          events: {
            click: handlePointClick
          }
        }
      },
      title: {
        text: 'Customers over time'
      },
      credits: {
        enabled: false
      },
      tooltip: {
        pointFormat: pointFormat
      },
      yAxis: yAxis,
      xAxis: xAxis,
      series: [
        {
          name: 'All Clients',
          data: allClients
        }, {
          name: 'Trial Clients',
          data: trialClients
        }, {
          name: 'Paying Clients',
          data: paidClients
        }
      ]
    });
    monthAgo = Date.now() - 2592000000;
    $('#container2').highcharts({
      chart: {
        type: 'line'
      },
      plotOptions: {
        line: {
          color: grey
        }
      },
      title: {
        text: 'Customers in the last 30 days'
      },
      yAxis: yAxis,
      xAxis: xAxis,
      series: [
        {
          name: 'All Clients',
          data: _.filter(allClients, function(point) {
            return point.x >= monthAgo;
          })
        }, {
          name: 'Trial Clients',
          data: _.filter(trialClients, function(point) {
            return point.x >= monthAgo;
          })
        }, {
          name: 'Paying Clients',
          data: _.filter(paidClients, function(point) {
            return point.x >= monthAgo;
          })
        }
      ]
    });
    weekAgo = Date.now() - 604800000;
    return $('#container3').highcharts({
      chart: {
        type: 'line'
      },
      plotOptions: {
        line: {
          color: grey
        }
      },
      title: {
        text: 'Customers in the last 7 days'
      },
      yAxis: yAxis,
      xAxis: xAxis,
      series: [
        {
          name: 'All Clients',
          data: _.filter(allClients, function(point) {
            return point.x >= weekAgo;
          })
        }, {
          name: 'Trial Clients',
          data: _.filter(trialClients, function(point) {
            return point.x >= weekAgo;
          })
        }, {
          name: 'Paying Clients',
          data: _.filter(paidClients, function(point) {
            return point.x >= weekAgo;
          })
        }
      ]
    });
  });

}).call(this);
